inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  Exclude:
    - "templates/**/*"

Style/Documentation:
  Exclude:
    - "lib/cequel/version.rb"
    - "lib/cequel/errors.rb"
    - "lib/cequel/record/errors.rb"

Style/HashSyntax:
  Exclude:
    - "lib/cequel/record/tasks.rb"

Style/IfUnlessModifier:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
